# -*- coding: utf-8 -*-
"""IA - Actividad 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQT1tveszZaQJnQqHCNV3ox6SzZTT7S_
"""

import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

# Cargar el nuevo conjunto de datos
URL = "https://raw.githubusercontent.com/SindyLancheros22/IA_Act_3_4/main/bd_masivo2.csv"
data = pd.read_csv(URL)

# Mostrar las primeras filas del conjunto de datos
print(data.head())

data.columns

# Seleccionar solo las características numéricas
X = data[['Pasajeros/dia', 'Variacion Transmilenio', 'Pasajeros dia tipico laboral', 'Pasajeros dia sabado', 'Pasajeros dia festivo']]

# Escalar los datos para que todas las características tengan media 0 y varianza 1
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Entrenar el modelo de DBSCAN
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan.fit(X_scaled)

# Asignar las etiquetas de los clústeres a cada punto de datos
data['Cluster'] = dbscan.labels_

# Mostrar la cantidad de elementos en cada clúster
print(data['Cluster'].value_counts())